### ISSUE TITLE
Interpolate variables in tokens and keys

### ISSUE THREAD

**Issue by garthk** [launchdarkly/ld-vscode#15]
[VS Code apparently provides for variable expansion from the environment](https://code.visualstudio.com/docs/editor/variables-reference), so I'd hoped I could avoid inhaling secrets into my settings by inhaling them from the environment instead:
```json
{"launchdarkly.sdkKey": "${env:LAUNCH_DARKLY_SDK_KEY}"}
```
It doesn't work. Is this under your control?

**Comment by atrakh** [comment]
Hi @garthk,

Unfortunately, this pattern is not currently supported by VSCode: https://github.com/microsoft/vscode/issues/2809.

For now, I'd recommend not checking your SDK key into your repo as we either wait for VSCode to support this functinoality or come up with a workaround. I can see the extension potentially consuming an external configuration file, but it's not something we're planning to build at this time.

**Comment by atrakh** [comment]
The `LaunchDarkly: Configure` command introduced in [2.2.0](https://github.com/launchdarkly/ld-vscode/releases) automatically configures the extension with secrets stored in extension storage instead of the `settings.json` file.

I know this isn't exactly what you asked for, but this solution should resolve any issues regarding storing secrets in `settings.json`. Please try out the latest version of the extension and let me know if you have any questions.

Cheers!
