### ISSUE TITLE
Extension causes high cpu load

### ISSUE THREAD

**Issue by dishui** [launchdarkly/ld-vscode#95]
- Issue Type: `Performance`
- Extension Name: `launchdarkly`
- Extension Version: `3.0.6`
- OS Version: `Darwin x64 21.6.0`
- VS Code version: `1.71.2`

:warning: Make sure to **attach** this file from your *home*-directory:
:warning:`file:///var/folders/5s/991mk8w56_j_djvjmqm24rv80000gq/T/launchdarklyofficial.launchdarkly-unresponsive.cpuprofile.txt`

Find more details here: https://github.com/microsoft/vscode/wiki/Explain-extension-causes-high-cpu-load

**Comment by InTheCloudDan** [comment]
@dishui thank you for the report! We have a `pre-release` version of the extension available that is version `3.9.0`. Would you mind giving it a try and seeing if that resolves the issue? When you install the update, you may need to click on the `Migrate Configuration` button under the Feature Flag treeview. This is because previously there was always a global configuration which meant every VS Code window opened started up the LaunchDarkly extension. Feedback we have received though is a majority of users may only end up using LaunchDarkly with a subset of the total workspaces they open so wanted it to be configured per workspace.

Please let us know if you have any feedback. I'd be happy to reach out via email for additional conversations.

![CleanShot 2022-10-07 at 08 28 48](https://user-images.githubusercontent.com/10308834/194553434-4abfabe0-3bbf-4c24-9c99-e54ec94c0330.png)
 
![CleanShot 2022-10-07 at 08 26 18](https://user-images.githubusercontent.com/10308834/194553018-b9369417-d2f7-43a0-94ed-65e64de1ac72.png)

**Comment by InTheCloudDan** [comment]
@dishui if you're still experiencing this issue please feel free to re-open the issue.
